### ISSUE TITLE
problem related to man file generation during build

### ISSUE THREAD

**Issue by IlgazC** [systemd/zram-generator#166]
When I try to build on completely updated Lubuntu 20.04 I get the following:

```
Finished release [optimized] target(s) in 1m 34s
sed -e 's,@SYSTEMD_SYSTEM_GENERATOR_DIR@,/lib/systemd/system-generators,' \
        < units/systemd-zram-setup@.service.in \
        > units/systemd-zram-setup@.service
ronn --organization="zram-generator developers" man/*.md
     roff: man/zram-generator.conf.md.5               
Traceback (most recent call last):
        35: from /usr/bin/ronn:184:in `<main>'
        34: from /usr/bin/ronn:184:in `each'
        33: from /usr/bin/ronn:199:in `block in <main>'
        32: from /usr/bin/ronn:199:in `each'
        31: from /usr/bin/ronn:209:in `block (2 levels) in <main>'
        30: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:240:in `convert'
        29: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `to_roff'
        28: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:245:in `new'
        27: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:18:in `initialize'
        26: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:91:in `block_filter'
        25: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
        24: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
        23: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
        22: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
        21: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
        20: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:160:in `block_filter'
        19: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
        18: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
        17: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
        16: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
        15: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
        14: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:172:in `block_filter'
        13: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block_filter'
        12: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
        11: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
        10: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         9: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:88:in `block in block_filter'
         8: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:120:in `block_filter'
         7: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `inline_filter'
         6: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
         5: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
         4: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         3: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:243:in `block in inline_filter'
         2: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `inline_filter'
         1: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `write'
/usr/lib/ruby/vendor_ruby/ronn/roff.rb:354:in `gsub': incompatible encoding regexp match (Windows-31J regexp with UTF-8 string) (Encoding::CompatibilityError)
make: *** [Makefile:41: man] Error 1
 ```

**Comment by nabijaczleweli** [comment]
Sounds like https://github.com/apjanke/ronn-ng/issues/54

**Comment by keszybz** [comment]
Yep, it sounds like an outdated ronn version. Lubuntu  20.04 is not even supported anymore.
